In [8]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent
CSV_DIR = PROJECT_ROOT / "data" / "raw" / "synthea_csv"

patients = pd.read_csv(CSV_DIR / "patients.csv", low_memory=False)
encounters = pd.read_csv(CSV_DIR / "encounters.csv", low_memory=False)
conditions = pd.read_csv(CSV_DIR / "conditions.csv", low_memory=False)
medications = pd.read_csv(CSV_DIR / "medications.csv", low_memory=False)
observations = pd.read_csv(CSV_DIR / "observations.csv", low_memory=False)

print("Patients:", len(patients))
print("Encounters:", len(encounters))
print("Conditions:", len(conditions))
print("Medications:", len(medications))
print("Observations:", len(observations))

Patients: 113
Encounters: 7957
Conditions: 4407
Medications: 5445
Observations: 103918

In [9]:
selected = pd.read_csv(PROJECT_ROOT / "data" / "selected_patients" / "selected_patient_cohort.csv")

selected.head(10)

,patient_id,encounter_count,medication_count,abnormal_observation_count,has_multiple_medications,has_abnormal_observations,has_meaningful_encounters,selection_score
0,2b36a3c6-e9d6-554e-28c3-a8244a67a553,233,534,0,True,False,True,35
1,976e3f24-1d50-efda-229a-1e6d1714f0cd,483,526,0,True,False,True,35
2,90d3751f-f4a6-b742-aa46-dd3112d60e5a,516,469,0,True,False,True,35
3,7f116ec2-58eb-a0d4-2682-7a0738b20b35,94,419,0,True,False,True,35
4,b23188ac-9529-2450-e0b7-58adb2b38de6,318,401,0,True,False,True,35
5,4a95bdc7-c1f1-8a09-509a-cf6bef54fc75,99,283,0,True,False,True,35
6,8bc57471-bff5-002f-914a-e812583bf95d,133,204,0,True,False,True,35
7,171a2edf-e42a-364e-6b06-0c17b5af82b5,376,200,0,True,False,True,35
8,40e66c47-f6e8-c2e7-6be6-dbc4b4fabe8d,466,168,0,True,False,True,35
9,22bf078d-30b6-9002-8ce9-f95d7804d9b5,76,119,0,True,False,True,35

In [10]:
patient_id = selected.iloc[0]["patient_id"]

patient_encounters = encounters[encounters["PATIENT"] == patient_id].copy()

patient_medications = medications[medications["PATIENT"] == patient_id].copy()

patient_observations = observations[observations["PATIENT"] == patient_id].copy()

display(patient_encounters.head())
display(patient_medications.head())
display(patient_observations.head())

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
4294,2b36a3c6-e9d6-554e-4d26-04028115dcc5,1965-03-18T03:00:20Z,1965-03-18T03:34:48Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,104079d4-560e-3eb8-9a48-d495835a3997,527e9155-4326-3132-aa3e-8f84a5e49353,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,162673000,General examination of patient (procedure),136.80,704.20,0.0,NaN,NaN
4295,2b36a3c6-e9d6-554e-f35c-431f2674f561,1983-08-18T03:00:20Z,1983-08-18T03:54:38Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,9d989fcf-4ad9-3972-ada3-f275d967781e,1ac08d2c-ae58-3339-9e6e-a2a9f463ac67,e03e23c9-4df1-3eb6-a62d-f70f02301496,outpatient,185349003,Encounter for check up (procedure),85.55,652.95,0.0,NaN,NaN
4296,2b36a3c6-e9d6-554e-6032-5e610c2ed0a0,1985-08-29T03:00:20Z,1985-08-29T03:30:29Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,9d989fcf-4ad9-3972-ada3-f275d967781e,1ac08d2c-ae58-3339-9e6e-a2a9f463ac67,e03e23c9-4df1-3eb6-a62d-f70f02301496,outpatient,185349003,Encounter for check up (procedure),85.55,1095.05,0.0,NaN,NaN
4297,2b36a3c6-e9d6-554e-d6f5-818060c73af6,1986-09-11T03:00:20Z,1986-09-11T03:34:40Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,104079d4-560e-3eb8-9a48-d495835a3997,527e9155-4326-3132-aa3e-8f84a5e49353,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,162673000,General examination of patient (procedure),136.80,1197.64,0.0,NaN,NaN
4298,2b36a3c6-e9d6-554e-3790-974ab2181bf1,1987-09-17T03:00:20Z,1987-09-17T03:33:43Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,104079d4-560e-3eb8-9a48-d495835a3997,527e9155-4326-3132-aa3e-8f84a5e49353,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,162673000,General examination of patient (procedure),136.80,1069.06,0.0,NaN,NaN

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION
2335,1990-10-25T03:00:20Z,2015-04-02T03:00:20Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,e03e23c9-4df1-3eb6-a62d-f70f02301496,2b36a3c6-e9d6-554e-548c-94e7156e9423,314231,Simvastatin 10 MG Oral Tablet,0.30,0.00,10,3.00,55822004.0,Hyperlipidemia (disorder)
2336,1991-10-17T03:00:20Z,NaN,2b36a3c6-e9d6-554e-28c3-a8244a67a553,e03e23c9-4df1-3eb6-a62d-f70f02301496,2b36a3c6-e9d6-554e-3526-a284935c08e1,312961,Simvastatin 20 MG Oral Tablet,41.93,0.00,288,12075.84,NaN,NaN
2337,1991-10-17T03:00:20Z,NaN,2b36a3c6-e9d6-554e-28c3-a8244a67a553,e03e23c9-4df1-3eb6-a62d-f70f02301496,2b36a3c6-e9d6-554e-3526-a284935c08e1,866412,24 HR metoprolol succinate 100 MG Extended Rel...,129.94,0.00,288,37422.72,NaN,NaN
2338,1991-10-17T03:00:20Z,NaN,2b36a3c6-e9d6-554e-28c3-a8244a67a553,e03e23c9-4df1-3eb6-a62d-f70f02301496,2b36a3c6-e9d6-554e-3526-a284935c08e1,705129,Nitroglycerin 0.4 MG/ACTUAT Mucosal Spray,28.29,0.00,288,8147.52,NaN,NaN
2339,1992-12-21T03:00:20Z,NaN,2b36a3c6-e9d6-554e-28c3-a8244a67a553,df166300-5a78-3502-a46a-832842197811,2b36a3c6-e9d6-554e-7fef-ae9213f78cba,849574,Naproxen sodium 220 MG Oral Tablet,91.72,41.72,273,25039.56,239872002.0,Osteoarthritis of hip (disorder)

,DATE,PATIENT,ENCOUNTER,CATEGORY,CODE,DESCRIPTION,VALUE,UNITS,TYPE
51198,2005-06-30T03:00:20Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,2b36a3c6-e9d6-554e-71b2-7aa9aac546e6,laboratory,2345-7,Glucose [Mass/volume] in Serum or Plasma,117.7,mg/dL,numeric
51199,2005-06-30T03:00:20Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,2b36a3c6-e9d6-554e-71b2-7aa9aac546e6,laboratory,3094-0,Urea nitrogen [Mass/volume] in Serum or Plasma,16.3,mg/dL,numeric
51200,2005-06-30T03:00:20Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,2b36a3c6-e9d6-554e-71b2-7aa9aac546e6,laboratory,2160-0,Creatinine [Mass/volume] in Serum or Plasma,2.1,mg/dL,numeric
51201,2005-06-30T03:00:20Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,2b36a3c6-e9d6-554e-71b2-7aa9aac546e6,laboratory,17861-6,Calcium [Mass/volume] in Serum or Plasma,8.6,mg/dL,numeric
51202,2005-06-30T03:00:20Z,2b36a3c6-e9d6-554e-28c3-a8244a67a553,2b36a3c6-e9d6-554e-71b2-7aa9aac546e6,laboratory,2951-2,Sodium [Moles/volume] in Serum or Plasma,143.8,mmol/L,numeric